[program:begonia-web]
directory=/opt/begonia
command=/usr/bin/python3 /opt/begonia/webapp/app.py
autostart=true
autorestart=true
startretries=10
stopsignal=TERM
stopwaitsecs=10
user=begonia
environment=HOST="127.0.0.1",PORT="8080",BEGONIA_DB="/var/lib/begonia/begonia.db"
stdout_logfile=/var/log/begonia/web.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stderr_logfile=/var/log/begonia/web.err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=10
